### ISSUE TITLE
Multiple Countries Exporter

### ISSUE THREAD

**Issue by joshuagibeonm** [guaychou/corona-prometheus-exporter#1]
I want to export multiple countries using one same process, but i can't do that because of limitation of the program itself. I've tried (not really) to use multiple processes but it's not feasible if we want to export ALL countries at the same time.

I think this feature is quite important because there's a little chance that people who use this program will only monitor one country.

We can make the program to accept multiple countries input using JSON/YAML file, and then recursively make a request to corona-API. Finally we can recursively register the gauges to prometheus.

**Comment by guaychou** [comment]
Done dude, but still no json/yaml file, just with cli. I think it's powerfull when you deploy it with container

**Comment by guaychou** [comment]
That's pull request has been merged [link](https://github.com/guaychou/corona-prometheus-exporter/pull/2)
